name: microm8 # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary:  microm8 Apple ][ emulator
description: |
   microm8 Apple ][ emulator

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  microm8_icon.png
title: Microm8

apps:
  microm8:
    command: microm8
parts:
  microm8:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      microm8: build/
      microm8.1: man/man1/

architectures:
  - build-on: amd64

